<a href="https://colab.research.google.com/github/shaifashala/DailyReport/blob/master/Day3(17June).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

EXAMPLE

In [82]:
#Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)


0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


In [83]:
#2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type

import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)


0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


EXERCISE

In [84]:
#1.Write a Pandas program to create and display a one-dimensional array using series containing event numbers upto 10000
# ds = pd.Series([0,2, 4, 6, 8..... 10000])

import pandas as pd
ds = pd.Series([x for x in range(1000) if x%2==0])
print(ds)


0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64


In [85]:
#2.Write a Pandas program to convert a Panda module Series of the numbers which are between 1000 and 2000 (both inclusive) and divisable by 5 to Python list and after convertion print its type
#[ ]
import pandas as pd
ds = pd.Series([x for x in range(1000,2000) if x%5==0])
print(ds)

0      1000
1      1005
2      1010
3      1015
4      1020
       ... 
195    1975
196    1980
197    1985
198    1990
199    1995
Length: 200, dtype: int64


In [86]:
#3.Write a Pandas program to add, subtract, multiple and divide two Pandas Series and print their results using the Sample Series: [2, 4, 6, 8, ...100], [1, 3, 5, 7, 9...99]
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
ds = ds1 + ds2
print("Add two Series:")
print(ds)
print("Subtract two Series:")
ds = ds1 - ds2
print(ds)
print("Multiply two Series:")
ds = ds1 * ds2
print(ds)
print("Divide Series1 by Series2:")
ds = ds1 / ds2
print(ds)

Add two Series:
0     3
1     7
2    11
3    15
4    19
dtype: int64
Subtract two Series:
0    1
1    1
2    1
3    1
4    1
dtype: int64
Multiply two Series:
0     2
1    12
2    30
3    56
4    90
dtype: int64
Divide Series1 by Series2:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64


In [87]:
#4.Write a Pandas program to compare (Equivalence, greater than, less than, not equal to )the elements of the two Pandas Series.
#Sample Series: [All positive numbers divisable by 7 upto 1000], [All positive numbers divisable by 11 upto 1000]
#Code:-
import pandas as pd
ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 10])
print("Series1:")
print(ds1)
print("Series2:")
print(ds2)
print("Compare the elements of the said Series:")
print("Equals:")
print(ds1 == ds2)
print("Greater than:")
print(ds1 > ds2)
print("Less than:")
print(ds1 < ds2)


Series1:
0     2
1     4
2     6
3     8
4    10
dtype: int64
Series2:
0     1
1     3
2     5
3     7
4    10
dtype: int64
Compare the elements of the said Series:
Equals:
0    False
1    False
2    False
3    False
4     True
dtype: bool
Greater than:
0     True
1     True
2     True
3     True
4    False
dtype: bool
Less than:
0    False
1    False
2    False
3    False
4    False
dtype: bool


In [88]:
#5.Write a Pandas program to convert a NumPy array to a Pandas series.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000]
import numpy as np
import pandas as pd
np_array = np.array([10, 20, 30, 40, 50])
print("NumPy array:")
print(np_array)
new_series = pd.Series(np_array)
print("Converted Pandas series:")
print(new_series)

NumPy array:
[10 20 30 40 50]
Converted Pandas series:
0    10
1    20
2    30
3    40
4    50
dtype: int64


In [89]:
#6.Write a Pandas program to convert a given Series to an array.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
#Code:-
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
print (a)

Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '400' '500' 'python' '300.12' '400' 'is' 'great'
 'language']


In [90]:
#7.Write a Pandas program to sort a given Series.
#Sample series is ['100', '200', ‘300’,’400’,’500’,'python', '300.12', '400',’is’,’great’,’language’]
#Code:-
import pandas as pd
import numpy as np
s1 = pd.Series(['100', '200', '300','400','500','python', '300.12', '400','is','great','language'])
print("Original Data Series:")
print(s1)
print("Series to an array")
a = np.array(s1.values.tolist())
a.sort()
print (a)


Original Data Series:
0          100
1          200
2          300
3          400
4          500
5       python
6       300.12
7          400
8           is
9        great
10    language
dtype: object
Series to an array
['100' '200' '300' '300.12' '400' '400' '500' 'great' 'is' 'language'
 'python']


In [91]:
#8.Write a Pandas program to create a subsets of a given series based on value and condition.
#Sample NumPy array: d1 = [10, 20, 30, 40, 50... 1000] value and condtion : Subset 1 :numbers divisable by 7 Subset 2 : numbers divisable by 5
#Code:-
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:")
print(s)
print("\nSubset of the above Data Series:")
n = 6
new_s = s[s < n]
print(new_s)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64

Subset of the above Data Series:
0    0
1    1
2    2
3    3
4    4
5    5
dtype: int64


In [92]:
#9.Write a Pandas program to create the mean and standard deviation, maximum and minimum of the data of a given Series of the prime numbers upto 1000
#Code:-
import pandas as pd
s = pd.Series(data = [x for x in range(1000) if x%2==0])
print("Original Data Series:")
print(s)
print("Mean of the said Data Series:")
print(s.mean())
print("Standard deviation of the said Data Series:")
print(s.std())

Original Data Series:
0        0
1        2
2        4
3        6
4        8
      ... 
495    990
496    992
497    994
498    996
499    998
Length: 500, dtype: int64
Mean of the said Data Series:
499.0
Standard deviation of the said Data Series:
288.9636655359978


In [93]:
#10.Write a Pandas program to get the elements of an array values into column-wise.
#Sample data: {‘X’:[All odd numbers but not divisable by 7 upto 1000], 'Y':[ All even numbers but not divisable by 5 upto 1000 ],'Z':[ All odd numbers but not divisable by 3 upto 1000]}
#Code:-
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]});
print(df)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [104]:
#11.Write a NumPy program to create a random 4x4 array and extract the 2nd and 3rd rows of the array and store them into a variable
#Code:-
import numpy as np
x = np.random.random((4,4))
print("Original Array:")
print(x) 

Original Array:
[[0.43664703 0.65889013 0.84812703 0.93670843]
 [0.59190687 0.29344696 0.01199781 0.3588173 ]
 [0.49313076 0.9193476  0.09259804 0.62953341]
 [0.90735947 0.37905416 0.8559937  0.16897216]]


In [103]:
#12.Write a NumPy program to create a 10x10 array with random values and find the minimum and maximum values.
#Code:-
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[2.79531640e-01 7.58014636e-01 5.18082797e-02 9.88344736e-01
  6.44171916e-01 4.48424125e-01 5.69334828e-01 8.76839333e-01
  8.91125445e-02 2.33134899e-01]
 [3.25324535e-02 4.30651638e-01 3.75204572e-01 8.70431166e-01
  8.35929462e-01 9.75450465e-01 4.15498283e-01 5.88638114e-04
  7.25993373e-01 7.93727086e-01]
 [1.35772610e-02 4.42408238e-01 9.15086915e-01 2.80512842e-01
  7.36744688e-02 5.43418637e-01 5.44734626e-01 7.26431418e-01
  4.51848792e-01 2.35969043e-01]
 [3.36286350e-01 1.45009248e-01 9.20199181e-01 1.29430703e-02
  4.32466425e-01 1.33227711e-01 3.04051359e-01 5.49280067e-01
  1.57393007e-01 6.89424791e-01]
 [1.87495416e-01 3.01369363e-02 8.29876490e-01 1.05803188e-02
  9.64678874e-01 1.46148502e-01 2.03895556e-01 8.21634837e-01
  3.24125892e-01 1.73733105e-01]
 [9.70023360e-02 6.21716106e-01 9.75486403e-01 2.48309581e-01
  6.11400397e-01 7.69496871e-01 6.10602308e-01 4.15131754e-01
  6.77231622e-01 1.63301766e-01]
 [1.90582128e-01 9.44036048e-01 7.02333738

In [102]:
#13.Write a NumPy program to generate 8 random integers between 100 and 300
#Code:-
import numpy as np
x = np.random.randint(low=100, high=300, size=8)
print(x)



[185 136 205 297 236 182 286 219]


In [101]:
#14.Write a NumPy program to create a random integer nos of size 20 and sort it
#Code:-
import numpy as np
x = np.random.random(20)
print("Original array:")
print(x)
x.sort()
print("Sorted array:")
print(x)

Original array:
[0.87491021 0.06844806 0.42441615 0.91207874 0.69263761 0.1836315
 0.50231359 0.18723623 0.10218948 0.05078641 0.12889802 0.72054824
 0.25549592 0.83436048 0.61524207 0.87286958 0.60326625 0.08726336
 0.20963524 0.59418842]
Sorted array:
[0.05078641 0.06844806 0.08726336 0.10218948 0.12889802 0.1836315
 0.18723623 0.20963524 0.25549592 0.42441615 0.50231359 0.59418842
 0.60326625 0.61524207 0.69263761 0.72054824 0.83436048 0.87286958
 0.87491021 0.91207874]
